plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\simply\\proj\\wind\\example\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "turbo run build --filter example"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]